title: Hyein Kim
description: Personal site
markdown: kramdown

collections:
  abcd:
    output: true
    permalink: /abcd/:name/
  projects:
    output: true
    permalink: /projects/:name/

defaults:
  - scope:
      path: ""
      type: abcd
    values:
      layout: abcd_layout
  - scope:
      path: ""
      type: projects
    values:
      layout: project_layout
